services:
  webserver:
    image: php:7.4.3-apache
    ports:
      - "8181:80"
    volumes:
      - ./workspace:/workspace/www/html
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}  # This is injected from GitHub Secrets in codespace and in local environment you need to create a file named .env and save your passord for the database service
    ports:
      - "6033:3306"
    volumes:
      - db_data26:/var/lib/mysql
      - ./workspace:/workspace
  phpmyadmin:
    image: phpmyadmin
    depends_on:
      - db
    restart: always
    ports:
      - '88:80'
    environment:
      PMA_HOST: db
volumes:
  db_data26:
